### ISSUE TITLE
Getting a bunch of errors in console!

### ISSUE THREAD

**Issue by aziz** [travmik/ZenTabs#5]
using ST 2.0.2, build 2221

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./ZenTabsTest.py", line 3, in <module>
    from mock import MagicMock
ImportError: No module named mock

Traceback (most recent call last):
  File "./sublime_plugin.py", line 195, in on_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 194, in <lambda>
  File "./ZenTabs.py", line 55, in on_modified
  File "./ZenTabs.py", line 19, in renew_list
  File "./ZenTabs.py", line 27, in get_view_by_id
AttributeError: 'NoneType' object has no attribute 'views'
Traceback (most recent call last):
  File "./sublime_plugin.py", line 205, in on_activated
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 204, in <lambda>
  File "./ZenTabs.py", line 42, in on_activated
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "./sublime_plugin.py", line 205, in on_activated
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 204, in <lambda>
  File "./ZenTabs.py", line 42, in on_activated
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "./sublime_plugin.py", line 205, in on_activated
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 204, in <lambda>
  File "./ZenTabs.py", line 42, in on_activated
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "./sublime_plugin.py", line 205, in on_activated
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 204, in <lambda>
  File "./ZenTabs.py", line 42, in on_activated
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "./sublime_plugin.py", line 205, in on_activated
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 204, in <lambda>
  File "./ZenTabs.py", line 42, in on_activated
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "./sublime_plugin.py", line 205, in on_activated
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 204, in <lambda>
  File "./ZenTabs.py", line 42, in on_activated
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "./sublime_plugin.py", line 195, in on_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 194, in <lambda>
  File "./ZenTabs.py", line 55, in on_modified
  File "./ZenTabs.py", line 19, in renew_list
  File "./ZenTabs.py", line 27, in get_view_by_id
AttributeError: 'NoneType' object has no attribute 'views'
Traceback (most recent call last):
  File "./sublime_plugin.py", line 195, in on_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 194, in <lambda>
  File "./ZenTabs.py", line 55, in on_modified
  File "./ZenTabs.py", line 19, in renew_list
  File "./ZenTabs.py", line 27, in get_view_by_id
AttributeError: 'NoneType' object has no attribute 'views'
Traceback (most recent call last):
  File "./sublime_plugin.py", line 195, in on_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 194, in <lambda>
  File "./ZenTabs.py", line 55, in on_modified
  File "./ZenTabs.py", line 19, in renew_list
  File "./ZenTabs.py", line 27, in get_view_by_id
AttributeError: 'NoneType' object has no attribute 'views'
Traceback (most recent call last):
  File "./sublime_plugin.py", line 195, in on_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 194, in <lambda>
  File "./ZenTabs.py", line 55, in on_modified
  File "./ZenTabs.py", line 19, in renew_list
  File "./ZenTabs.py", line 27, in get_view_by_id
AttributeError: 'NoneType' object has no attribute 'views'
Traceback (most recent call last):
  File "./sublime_plugin.py", line 195, in on_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 194, in <lambda>
  File "./ZenTabs.py", line 55, in on_modified
  File "./ZenTabs.py", line 19, in renew_list
  File "./ZenTabs.py", line 27, in get_view_by_id
AttributeError: 'NoneType' object has no attribute 'views'
```

**Comment by travmik** [comment]
thank you. I am investigating this problem now.
I even have it in todo ;)

**Comment by aziz** [comment]
:wink:  BTW, Thanks for your awesome PR for PlainTasks

**Comment by travmik** [comment]
Thank you. I have several ideas for your great plugin but haven't time now for consider them to code or even to enhancement request. Will be in touch :metal:

**Comment by travmik** [comment]
Looks like ST on load time has not active_window. I've added checking for None but I actually don't like this solution. Still think about this.
